apiVersion: v1
kind: Secret
metadata:
  name: moysklad-reco-db
type: Opaque
stringData:
  url: jdbc:postgresql://<managed-pg-host>:5432/moysklad_reco
  username: moysklad_reco
  password: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: moysklad-reco-vendor
type: Opaque
stringData:
  appUid: "<appUid_из_кабинета_разработчика>"
  secretKey: "<secretKey_из_кабинета_разработчика>"

